<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ReqModel" nsURI="eu.modelwriter.architecture.textconnectors.docx.reqmodel"
    nsPrefix="ReqModel">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.diagram"/>
    <eAnnotations source="gmf.node">
      <details key="label" value="Name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OwnedDefinition" upperBound="-1"
        eType="#//Definition" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementLevel" eSuperTypes="#//Definition">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="label.icon" value="true"/>
      <details key="label" value="Name"/>
      <details key="label.pattern" value="{0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OwnedDefinition" upperBound="-1"
        eType="#//Definition" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//Definition">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rounded"/>
      <details key="label.icon" value="true"/>
      <details key="label" value="Name"/>
      <details key="label.pattern" value="{0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Refine" eType="#//Requirement">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DependencyTo" eType="#//Requirement">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PriorityType" eType="#//Priority"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextArea" eSuperTypes="#//Definition">
    <eAnnotations source="gmf.node">
      <details key="label" value="Name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="Mandatory"/>
    <eLiterals name="Optional" value="1"/>
  </eClassifiers>
</ecore:EPackage>
