title: "Tarski: A Platform for Automated Analysis of Traceability"
description: "Automated Reasoning about Traces based on Configurable Formal Semantics"
show_downloads: true
theme: jekyll-theme-cayman
