<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BookStorePackage" nsURI="http:///com.ibm.dynamic.example.bookstore.ecore"
    nsPrefix="bookStore">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="lib" value="#/"/>
    <details key="mylib" value="Mylibrary.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BookStore" instanceClassName="instanceClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" eType="ecore:EClass library.ecore#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myBooks" eType="ecore:EClass library.ecore#//Book"/>
  </eClassifiers>
</ecore:EPackage>
