<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BookStorePackage" nsURI="http:///com.ibm.dynamic.example.bookstore.ecore"
    nsPrefix="bookStore">
  <eClassifiers xsi:type="ecore:EClass" name="A">
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
        <details key="visibility" value="public"/>
      </eAnnotations>
    <eOperations name="method" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" ordered="false"
        unique="false" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" ordered="false" lowerBound="1"
        eType="#//pack/B"/>
  </eClassifiers>
  <eSubpackages name="pack" nsURI="bla bla" nsPrefix="p">
    <eClassifiers xsi:type="ecore:EClass" name="B">
      <eAnnotations source="ferhat" references="#//A/owner Instance.requirements#B Instance.requirements#//@requirements.0/@parts.1 Instance.requirements#//@requirements.0/@parts.0 Instance.requirements#//@relationships.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" ordered="false"
          eType="ecore:EEnum Requirements.ecore#//Priority"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
