<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tutorial" nsURI="'http://www.eclipse.org/mdt/ocl/oclinecore/tutorial'" nsPrefix="tut">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/visibility">
      <details key="visibility" value="public"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/expression/derivation">
        <details key="expression" value="library.loans->selec"/>
      </eAnnotations>
      <eAnnotations source="sadasdas"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1" containment="true">
      <eAnnotations/>
      <eAnnotations source="sadasdas"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/expression/derivation">
        <details key="expression" value="library.loans->selec"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" upperBound="-1" containment="true">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/static"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/expression/invariant">
      <details key="callable" value="false"/>
      <details key="name" value="importantConstraint"/>
      <details key="message" value="multi&#xA;                                        lined&#xA;                                        message"/>
    </eAnnotations>
    <eOperations name="isAvailable">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/operation/body"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/operation/postcondition">
        <details key="name" value="sup"/>
        <details key="message" value="this is a precondition"/>
      </eAnnotations>
      <eParameters name="param1"/>
      <eParameters name="param2"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copies" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" upperBound="-1" volatile="true" derived="true">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/expression/derivation">
        <details key="expression" value="library.loans->selec"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member">
    <eOperations name="tespOP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" upperBound="-1" volatile="true" derived="true">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/expression/derivation">
        <details key="expression" value="library.loans->selec"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" unique="false" upperBound="-1" volatile="true" derived="true">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/expression/initial">
        <details key="expression" value="loans->collec"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loan">
    <eAnnotations/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" lowerBound="1"/>
  </eClassifiers>
  <eSubpackages name="Organization" nsURI="'http://www.eclipse.org/mdt/ocl/oclinecore/tutorial/organization'" nsPrefix="org">
    <eAnnotations source="extAnno"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Type" serializable="false">
      <eLiterals name="asd"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="JavaPackage" instanceClassName="java.lang.Package" serializable="false"/>
    <eClassifiers xsi:type="ecore:EClass" name="Librarian">
      <eOperations name="orgOpp"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="workOn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ref">
      <eStructuralFeatures xsi:type="ecore:EReference" name="RefOutsideEcore"/>
    </eClassifiers>
    <eSubpackages name="SubOrg1" nsURI="'suborg1'" nsPrefix="sb">
      <eClassifiers xsi:type="ecore:EClass" name="sb1C"/>
    </eSubpackages>
    <eSubpackages name="SubOrg2" nsURI="'SubOrg2'" nsPrefix="sb2">
      <eClassifiers xsi:type="ecore:EClass" name="sb2C"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
