/**
 *
 * $Id$
 */
package eu.modelwriter.alloyxmlapi.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import eu.modelwriter.alloyxmlapi.TupleType;
import eu.modelwriter.alloyxmlapi.TypesType;

/**
 * A sample validator interface for {@link eu.modelwriter.alloyxmlapi.FieldType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FieldTypeValidator {
  boolean validate();

  boolean validateMixed(FeatureMap value);
  boolean validateTuple(EList<TupleType> value);
  boolean validateTypes(TypesType value);
  boolean validateID(byte value);
  boolean validateLabel(String value);
  boolean validateParentID(byte value);
  boolean validateExpression(String value);
}
