/**
 *
 * $Id$
 */
package eu.modelwriter.alloyxmlapi.validation;

import org.eclipse.emf.common.util.EList;

import eu.modelwriter.alloyxmlapi.AtomType;

/**
 * A sample validator interface for {@link eu.modelwriter.alloyxmlapi.TupleType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TupleTypeValidator {
  boolean validate();

  boolean validateAtom(EList<AtomType> value);
}
