/*******************************************************************************
 * Copyright (c) 2015 UNIT Information Technologies R&D
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    A. Furkan Tanriverdi (UNIT) - initial API and implementation
 *******************************************************************************/
/**
 *
 * $Id$
 */
package DocModel.validation;

import DocModel.Paragraph;
import DocModel.Part;

import org.apache.poi.xwpf.usermodel.XWPFParagraph;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link DocModel.Paragraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParagraphValidator {
	boolean validate();

	boolean validateOwnedNode(EList<Paragraph> value);
	boolean validateParentNode(Paragraph value);
	boolean validateParagraph(XWPFParagraph value);
	boolean validateOwnedPart(EList<Part> value);
	boolean validateFirstPart(Part value);
}
