/**
 *
 * $Id$
 */
package eu.modelwriter.traceability.core.persistence.validation;

import eu.modelwriter.traceability.core.persistence.PropertiesType;

/**
 * A sample validator interface for {@link eu.modelwriter.traceability.core.persistence.MarkerType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarkerTypeValidator {
  boolean validate();

  boolean validateProperties(PropertiesType value);
  boolean validateLabel(String value);
}
