/**
 *
 * $Id$
 */
package eu.modelwriter.traceability.core.persistence.validation;

import eu.modelwriter.traceability.core.persistence.TupleType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.modelwriter.traceability.core.persistence.RelationType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationTypeValidator {
  boolean validate();

  boolean validateTuple(EList<TupleType> value);
}
