<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DocModel" nsURI="eu.modelwriter.architecture.textconnectors.docx.parser.documentmodel"
    nsPrefix="eu.modelwriter.architecture.textconnectors.docx.parser">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mark" eType="#//Mark" eOpposite="#//Mark/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParagraph" upperBound="-1"
        eType="#//Paragraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMark" upperBound="-1"
        eType="#//Mark" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mark" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node" eOpposite="#//Node/mark"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNode" upperBound="-1"
        eType="#//Paragraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPart" upperBound="-1"
        eType="#//Part" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstPart" eType="#//Part"
        eOpposite="#//Part/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextPart" eType="#//Part"
        eOpposite="#//Part/prevPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prevPart" eType="#//Part"
        eOpposite="#//Part/nextPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Paragraph"
        eOpposite="#//Paragraph/firstPart"/>
  </eClassifiers>
</ecore:EPackage>
