<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RequirementsMetamodel" nsURI="eu.modelwriter.demonstrations.alloyinecore.requirement"
    nsPrefix="Req">
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/import">
    <details key="Ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOf" upperBound="-1"
        eType="#//Requirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        upperBound="5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="defff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//test/RequirementPart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outref" eType="ecore:EClass Tutorial.ecore#//Loan"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="proposed"/>
    <eLiterals name="analyzed" value="1"/>
    <eLiterals name="accepted" value="2"/>
    <eLiterals name="rejected" value="3"/>
    <eLiterals name="replaced" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="neutral"/>
    <eLiterals name="lowCritical" value="1"/>
    <eLiterals name="critical" value="2"/>
    <eLiterals name="veryCritical" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Require" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="float" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="char" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigDec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refine" eSuperTypes="#//Relationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="PartiallyRefine" eSuperTypes="#//Relationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conflict" eSuperTypes="#//Relationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Contain" eSuperTypes="#//Relationship"/>
  <eSubpackages name="test" nsURI="test/test" nsPrefix="tt">
    <eClassifiers xsi:type="ecore:EClass" name="RequirementPart" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" eType="#//Status"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PartTypeA" eSuperTypes="#//test/RequirementPart"/>
    <eClassifiers xsi:type="ecore:EClass" name="PartTypeB" eSuperTypes="#//test/RequirementPart"/>
  </eSubpackages>
</ecore:EPackage>
