<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eAnnotations source="www.annotation.test">
    <eAnnotations source="www.sub.annotation.test" references="#//SubPackage/SubTestClass">
      <details key="testKey" value="testValue"/>
    </eAnnotations>
    <details key="testKey" value="testValue"/>
    <details key="testKey2" value="testValue2"/>
  </eAnnotations>
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/import">
    <details key="Ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass" instanceClassName="TCname">
    <eAnnotations source="www.annotation.test">
      <eAnnotations source="www.sub.annotation.test" references="#//TestDataType"/>
    </eAnnotations>
    <eOperations name="testOp" ordered="false" lowerBound="1">
      <eAnnotations source="www.annotation.test"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="www.annotation.test"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testRef" ordered="false"
        eType="#//SubPackage/SubTestClass">
      <eAnnotations source="www.annotation.test"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum" instanceClassName="TEname"
      serializable="false">
    <eAnnotations source="www.annotation.test"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TestDataType" instanceClassName="TDTname"
      serializable="false">
    <eAnnotations source="www.annotation.test"/>
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/datatype/primitive"/>
  </eClassifiers>
  <eSubpackages name="SubPackage" nsURI="www.sub.testpackage.org" nsPrefix="sp">
    <eAnnotations source="www.annotation.test"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestClass">
      <eAnnotations source="www.annotation.test"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestInterface" abstract="true"
        interface="true">
      <eAnnotations source="www.annotation.test"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SubTestEnum">
      <eAnnotations source="www.annotation.test"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="SubTestDataType" instanceClassName="STDTname">
      <eAnnotations source="www.annotation.test">
        <eAnnotations source="www.sub.annotation.test"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
