<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/import">
    <details key="Ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass" instanceClassName="TCname"
      eSuperTypes="#//SuperClass #//UberClass">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
      <details key="visibility" value="private"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="2017-01-01"
        unsettable="true" derived="true" iD="true">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/expression/derivation">
        <details key="expression" value="~testAttr"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/static"/>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/model"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testStringAttr" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/model"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testRealAttr" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="0.0">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/ghost"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testBooleanAttr" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" volatile="true"
        transient="true" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testIntAttr" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" transient="true"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr1" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr2" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr3" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr4" lowerBound="2"
        upperBound="5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr5" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testUnlimitedNaturalAttr"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr6" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr7" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr8" lowerBound="2"
        upperBound="5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestInterface" instanceClassName="TIname"
      abstract="true" interface="true" eSuperTypes="#//SuperClass"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum" instanceClassName="TEname"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TestDataType" instanceClassName="TDTname"
      serializable="false">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/datatype/primitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClass" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UberClass" abstract="true"/>
  <eSubpackages name="SubPackage" nsURI="www.sub.testpackage.org" nsPrefix="sp">
    <eClassifiers xsi:type="ecore:EClass" name="SubTestClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testIntAttr" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testStringAttr" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testRealAttr" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testBooleanAttr" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" transient="true"
          defaultValueLiteral="2016-09-09"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestInterface" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="SubTestEnum"/>
    <eClassifiers xsi:type="ecore:EDataType" name="SubTestDataType" instanceClassName="STDTname"/>
  </eSubpackages>
</ecore:EPackage>
