<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eAnnotations source="http://www.modelwriter.eu/alloyinecore/import">
    <details key="Ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass" instanceClassName="TCname"
      eSuperTypes="#//SuperClass #//UberClass">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
      <details key="visibility" value="private"/>
    </eAnnotations>
    <eOperations name="testOp" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//SubPackage/SubTestInterface #//SubPackage/SubTestClass">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/precondition">
        <details key="name" value="testPre"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="lone testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/body">
        <details key="name" value="testPre"/>
        <details key="expression" value="testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/postcondition">
        <details key="name" value="testPost"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="one testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/static"/>
      <eParameters name="testParam" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="testParam2" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eOperations>
    <eOperations name="testOp1" ordered="false" eType="#//TestDataType"/>
    <eOperations name="testOp2" ordered="false" lowerBound="1" eType="#//TestDataType"/>
    <eOperations name="testOp3" upperBound="-1" eType="#//TestDataType"/>
    <eOperations name="testOp4" lowerBound="1" upperBound="-1" eType="#//TestDataType"/>
    <eOperations name="testOp5" lowerBound="3" upperBound="6" eType="#//TestDataType"/>
    <eOperations name="testVoidOp" ordered="false" lowerBound="1">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/precondition">
        <details key="name" value="testPre"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="lone testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/body">
        <details key="name" value="testBody"/>
        <details key="expression" value="testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/postcondition">
        <details key="name" value="testPost"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="one testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/postcondition">
        <details key="name" value="testPost2"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="one testOp"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="testOp6" upperBound="-1" eType="#//TestDataType">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
    </eOperations>
    <eOperations name="testOp7" lowerBound="1" upperBound="-1" eType="#//TestDataType">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
    </eOperations>
    <eOperations name="testOp8" lowerBound="3" upperBound="6" eType="#//TestDataType">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
    </eOperations>
    <eOperations name="testOp9" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//SubPackage/SubTestInterface #//SubPackage/SubTestClass">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/precondition">
        <details key="name" value="testPre"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="lone testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/body">
        <details key="name" value="testPre"/>
        <details key="expression" value="testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/operation/postcondition">
        <details key="name" value="testPost"/>
        <details key="message" value="Hey!"/>
        <details key="formula" value="one testOp"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/static"/>
      <eParameters name="testParam" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
      </eParameters>
      <eParameters name="testParam2" lowerBound="2" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar">
        <eAnnotations source="http://www.modelwriter.eu/alloyinecore/nullable"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestInterface" instanceClassName="TIname"
      abstract="true" interface="true" eSuperTypes="#//SuperClass"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum" instanceClassName="TEname"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TestDataType" instanceClassName="TDTname"
      serializable="false">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/datatype/primitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClass" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UberClass" abstract="true"/>
  <eSubpackages name="SubPackage" nsURI="www.sub.testpackage.org" nsPrefix="sp">
    <eClassifiers xsi:type="ecore:EClass" name="SubTestClass"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestInterface" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="SubTestEnum"/>
    <eClassifiers xsi:type="ecore:EDataType" name="SubTestDataType" instanceClassName="STDTname"/>
  </eSubpackages>
</ecore:EPackage>
