<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eSubpackages name="SubPackage1" nsURI="www.sub1.testpackage.org" nsPrefix="sp1">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
      <details key="visibility" value="public"/>
    </eAnnotations>
    <eSubpackages name="SubSubPackage" nsURI="www.sub.sub1.testpackage.org" nsPrefix="ssp">
      <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="SubPackage2" nsURI="www.sub2.testpackage.org" nsPrefix="sp2"/>
</ecore:EPackage>
