<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tutorial" nsURI="'http://www.eclipse.org/mdt/ocl/oclinecore/tutorial'" nsPrefix="tut">
  <eClassifiers xsi:type="ecore:EClass" name="Library" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" changeable="false" iD="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" ordered="false" upperBound="-1" eType="//Book" changeable="false" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" ordered="false" upperBound="-1" eType="//Loan" changeable="false" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" ordered="false" upperBound="-1" eType="//Member" changeable="false" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Invariant">
      <details key="name" value="SufficientCopies"/>
      <details key="callable" value="false"/>
      <details key="formula" value="expr"/>
    </eAnnotations>
    <eOperations name="isAvailable" ordered="false">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Operation/Precondition"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Operation/Precondition">
        <details key="name" value="test"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Operation/Body">
        <details key="name" value="test"/>
        <details key="expression" value="expr"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Operation/Body">
        <details key="expression" value="expr"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" changeable="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copies" ordered="false" lowerBound="1" changeable="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" ordered="false" eType="//Library" changeable="false" resolveProxies="false" eOpposite="//Library/books"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" ordered="false" upperBound="-1" eType="//Loan" changeable="false" volatile="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Invariant">
      <details key="name" value="AtMostTwoLoans"/>
      <details key="callable" value="false"/>
      <details key="formula" value="expr"/>
    </eAnnotations>
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Invariant">
      <details key="name" value="UniqueLoans"/>
      <details key="callable" value="false"/>
      <details key="formula" value="expr"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" changeable="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" ordered="false" eType="//Library" changeable="false" resolveProxies="false" eOpposite="//Library/members"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loans" ordered="false" upperBound="-1" eType="//Loan" changeable="false" volatile="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" ordered="false" unique="false" upperBound="-1" eType="//Book" changeable="false" volatile="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" ordered="false" lowerBound="1" eType="//Book" changeable="false" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" ordered="false" lowerBound="1" eType="//Member" changeable="false" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" changeable="false"/>
  </eClassifiers>
  <eSubpackages name="Organization" nsURI="'http://www.eclipse.org/mdt/ocl/oclinecore/tutorial/organization'" nsPrefix="org">
    <eClassifiers xsi:type="ecore:EClass" name="Librarian" abstract="true" eSuperTypes="//Organization/Employee">
      <eStructuralFeatures xsi:type="ecore:EReference" name="workOn" ordered="false" lowerBound="1" eType="//Library" changeable="false" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true" eSuperTypes="//Library">
      <eStructuralFeatures xsi:type="ecore:EReference" name="RefOutsideEcore" ordered="false" changeable="false" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="JavaPackage" instanceClassName="'java.lang.Package'" serializable="false"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Type" serializable="false">
      <eLiterals name="type1"/>
      <eLiterals name="type2"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
