<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eAnnotations source="www.annotation.test">
    <eAnnotations source="www.sub.annotation.test" references="#//SubPackage/SubTestClass">
      <details key="testKey" value="testValue"/>
    </eAnnotations>
    <details key="testKey" value="testValue"/>
    <details key="testKey2" value="testValue2"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass" instanceTypeName="TCname">
    <eAnnotations source="www.annotation.test">
      <eAnnotations source="www.sub.annotation.test" references="#//TestDataType"/>
    </eAnnotations>
    <eOperations name="testOp">
      <eAnnotations source="www.annotation.test"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="www.annotation.test"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testRef" eType="#//SubPackage/SubTestClass">
      <eAnnotations source="www.annotation.test"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum" instanceTypeName="TEname">
    <eAnnotations source="www.annotation.test"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TestDataType" instanceTypeName="TDTname">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/DataType/Primitive"/>
    <eAnnotations source="www.annotation.test"/>
  </eClassifiers>
  <eSubpackages name="SubPackage" nsURI="www.sub.testpackage.org" nsPrefix="sp">
    <eAnnotations source="www.annotation.test"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestClass">
      <eAnnotations source="www.annotation.test"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestInterface" abstract="true"
        interface="true">
      <eAnnotations source="www.annotation.test"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SubTestEnum" serializable="false">
      <eAnnotations source="www.annotation.test"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="SubTestDataType" instanceTypeName="STDTname"
        serializable="false">
      <eAnnotations source="www.annotation.test">
        <eAnnotations source="www.sub.annotation.test"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
