<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Import">
    <details key="Ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass" instanceClassName="TCname"
      eSuperTypes="#//SuperClass #//UberClass">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Visibility">
      <details key="visibility" value="private"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="2017-01-01" unsettable="true"
        derived="true" iD="true">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Static"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Model"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Nullable"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Expression/Initial">
        <details key="expression" value="~testAttr"/>
      </eAnnotations>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Expression/Derivation">
        <details key="expression" value="~testAttr"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testStringAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Model"/>
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Nullable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testRealAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="0.0">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Ghost"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testBooleanAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        volatile="true" transient="true" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testIntAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true" defaultValueLiteral="1">
      <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/Visibility">
        <details key="visibility" value="private"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr2" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr3" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr4" lowerBound="2"
        upperBound="5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testUnlimitedNaturalAttr"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestInterface" instanceClassName="TIname"
      abstract="true" interface="true" eSuperTypes="#//SuperClass"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum" instanceClassName="TEname"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TestDataType" instanceClassName="TDTname">
    <eAnnotations source="http://www.modelwriter.eu/AlloyInEcore/DataType/Primitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClass" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UberClass" abstract="true"/>
  <eSubpackages name="SubPackage" nsURI="www.sub.testpackage.org" nsPrefix="sp">
    <eClassifiers xsi:type="ecore:EClass" name="SubTestClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testIntAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testStringAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testRealAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testBooleanAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
          transient="true" defaultValueLiteral="2016-09-09"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestInterface" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="SubTestEnum" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="SubTestDataType" instanceClassName="STDTname"
        serializable="false"/>
  </eSubpackages>
</ecore:EPackage>
