<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestPackage" nsURI="www.testpackage.org" nsPrefix="tp">
  <eClassifiers xsi:type="ecore:EClass" name="TestClass" instanceClassName="TCCname"
      eSuperTypes="#//SuperClass #//UberClass">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
      <details key="visibility" value="private"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestInterface" instanceClassName="TIname"
      abstract="true" interface="true" eSuperTypes="#//SuperClass">
    <eAnnotations source="http://www.modelwriter.eu/alloyinecore/visibility">
      <details key="visibility" value="public"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestEnum" instanceClassName="TEname"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TestDataType" instanceClassName="TDTname"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClass" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UberClass" abstract="true"/>
  <eSubpackages name="SubPackage" nsURI="www.sub.testpackage.org" nsPrefix="sp">
    <eClassifiers xsi:type="ecore:EClass" name="SubTestClass"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubTestInterface" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EEnum" name="SubTestEnum"/>
    <eClassifiers xsi:type="ecore:EDataType" name="SubTestDataType" instanceClassName="STDTname"/>
  </eSubpackages>
</ecore:EPackage>
