<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping" nsURI="http://www.modelwriter.eu/mapping" nsPrefix="mapping">
  <eClassifiers xsi:type="ecore:EClass" name="Location" abstract="true" eSuperTypes="#//IBaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        containment="true" eOpposite="#//Scope/holder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetLinks" upperBound="-1"
        eType="#//Link" containment="true" eOpposite="#//Link/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Location" containment="true" eOpposite="#//Location/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Location"
        eOpposite="#//Location/contents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencingScopes" upperBound="-1"
        eType="#//Scope" eOpposite="#//Scope/locations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" eSuperTypes="#//IBaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" lowerBound="1"
        upperBound="-1" eType="#//Location" eOpposite="#//Location/referencingScopes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holder" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/scope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//IBaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//Status" defaultValueLiteral="VALID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/targetLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/sourceLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    <eLiterals name="VALID"/>
    <eLiterals name="CHANGED_SOURCE" value="1"/>
    <eLiterals name="CHANGED_TARGET" value="2"/>
    <eLiterals name="DELETED_SOURCE" value="3"/>
    <eLiterals name="DELETED_TARGET" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Base" eSuperTypes="#//IBaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootLocations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBaseElement" abstract="true" interface="true"/>
</ecore:EPackage>
