<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doc2modelMapping"
    nsURI="http://www.topcased.org/doc2model/doc2modelMapping" nsPrefix="doc2modelMapping">
  <eClassifiers xsi:type="ecore:EClass" name="doc2model" eSuperTypes="#//DynamicElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//LinkedElement" containment="true" eOpposite="#//LinkedElement/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchy" eType="#//Hierarchy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkedElement" abstract="true" eSuperTypes="#//DynamicElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//doc2model"
        eOpposite="#//doc2model/links"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" eType="#//Hierarchy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocStyle" eSuperTypes="#//LinkedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hierarchy" eSuperTypes="#//DynamicElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subHierarchy" eType="#//Hierarchy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleValue" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagElement" eSuperTypes="#//LinkedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagAttribute" eSuperTypes="#//DynamicElement #//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="injection" lowerBound="1"
        eType="#//InjectionElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleAttribute" eSuperTypes="#//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//DynamicElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InjectionElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringFormat" eType="#//TextFormatter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="standardOptionalInjections"
        upperBound="-1" eType="#//InjectionElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="noname"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewClassInjection" eSuperTypes="#//INewClassInjection #//StereotpyeApplicableInjection #//InstanceCreationInjection #//ElementCreationInjection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owningClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationOwning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeForValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeAttributeForValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="browseTopContainersForOwner"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionInjection" eSuperTypes="#//DependantInjection #//StereotpyeApplicableInjection #//InstanceCreationInjection #//ElementCreationInjection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owningClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newInstanceForEachComposition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeInjection" eSuperTypes="#//DependantInjection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependantInjection" abstract="true"
      eSuperTypes="#//InjectionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsWith" eType="#//ElementCreationInjection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceInjection" eSuperTypes="#//DependantInjection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeToFind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classReferenced" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStereotypeReference"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegExAttribute" eSuperTypes="#//Attribute #//GroupElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegEx" eSuperTypes="#//LinkedElement #//RegExMatchingElement #//GroupElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewClassInjectionComposite" eSuperTypes="#//INewClassInjection #//ElementCreationInjection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="injections" upperBound="-1"
        eType="#//NewClassInjection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INewClassInjection" abstract="true"
      eSuperTypes="#//InjectionElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StereotpyeApplicableInjection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeToApply" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnMatchElement" eSuperTypes="#//LinkedElement #//ColumnElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegExMatchingElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regExToMatch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceCreationInjection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specificNamespaceURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnMatchAttribute" eSuperTypes="#//ColumnElement #//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnElement" abstract="true" eSuperTypes="#//RegExMatchingElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementCreationInjection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextFormatter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regexForConditionOrGroup"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryInjectionsForGroups"
        upperBound="-1" eType="#//DependantInjection" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
